### ISSUE TITLE
PDC integration

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/housekeeper#11]
@robinandeer

- [x] rename "archive" to "compile" (adds two assets, doesn't set date)
- [x] add checksum to asset record
- [x] delete tar assets + update with archived date

@ingkebil 

- ~~[ ] new table for archived assets on PDC~~
- [x] send to PDC

**Comment by ingkebil** [comment]
Fixed in 65dbeeb713a7a1bb6a0c9418dcca3438d07cc998
