### ISSUE TITLE
Deprecate tag `archived_sample_sheet` and replace by `samplesheet`

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/housekeeper#135]
## Description
We want to deprecate the tag `archived_sample_sheet`. All sample sheets should have the tag `sample_sheet` instead.

## Proposed solution
EDIT:
- [x] Iterate over all the Housekeeper bundles with either `archived_sample_sheet` or `samplesheet`, keep the one with the lastest ´timestamp as the proper `samplesheet` and delete the rest in Housekeeper and Hasta.
```python
import os
import sys

from housekeeper.store.models import File, Tag, Version

from cg.apps.housekeeper.hk import HousekeeperAPI


def get_hk_api_stage():
    return HousekeeperAPI()


def get_hk_api_prod():
    return HousekeeperAPI()


class SampleSheetTagUpdater:
    def __init__(self, hk_api: HousekeeperAPI, dry_run: bool):
        self.hk_api: HousekeeperAPI = hk_api
        self.dry_run: bool = dry_run
        self.sample_sheet_tag_name: str = "samplesheet"
        self.sample_sheet_tag: Tag = hk_api.get_tag(name=self.sample_sheet_tag_name)
        self.archived_sample_sheet_tag_name: str = "archived_sample_sheet"
        self.archived_sample_sheet_tag: Tag = hk_api.get_tag(
            name=self.archived_sample_sheet_tag_name
        )
        sample_sheet_bundles: list[str] = [
            file.version.bundle.name for file in self.sample_sheet_tag.files
        ]
        archived_sample_sheet_bundles: list[str] = [
            file.version.bundle.name for file in self.archived_sample_sheet_tag.files
        ]
        self.bundles = set(sample_sheet_bundles + archived_sample_sheet_bundles)

    def get_sample_sheets_for_bundle(self, bundle: str) -> list[File]:
        """Return a list with the sample sheets and archived sample sheets for a bundle."""
        sample_sheets: list[File] = self.hk_api.get_files_from_latest_version(
            bundle_name=bundle, tags=[self.sample_sheet_tag_name]
        ).all()
        archived_sample_sheets: list[File] = self.hk_api.get_files_from_latest_version(
            bundle_name=bundle, tags=[self.archived_sample_sheet_tag_name]
        ).all()
        return sample_sheets + archived_sample_sheets

    @staticmethod
    def file_production_path(file: File) -> str:
        """Return the production file path if is a stage file, otherwise return the full path."""
        if "/stage/" in file.full_path:
            return file.full_path.replace("/stage/", "/production/")
        return file.full_path

    def get_latest_file(self, files: list[File]) -> File:
        """Return the File with the most recent modification date from the given list."""
        valid_files_and_times = []
        for file in files:
            prod_path: str = self.file_production_path(file=file)
            if os.path.exists(prod_path):
                modified_time = os.path.getmtime(prod_path)
            else:
                modified_time = 0
            valid_files_and_times.append((file, modified_time))

        sorted_files = sorted(valid_files_and_times, key=lambda x: x[1], reverse=True)
        sorted_files = [pair[0] for pair in sorted_files]
        return sorted_files[0]

    def delete_files(self, files: list[File]):
        """Remove files from Housekeeper and Hasta."""
        for file in files:
            if not self.dry_run:
                self.hk_api.delete_file(file_id=file.id)
            else:
                print(
                    f"[DELETE-dry-run] Would have deleted {file.full_path} from Housekeeper"
                )

    def update_sample_sheet_tag(self, sample_sheet: File):
        """Replace the tag 'archived_sample_sheet' for 'samplesheet' if applicable."""
        if self.sample_sheet_tag in sample_sheet.tags:
            print(
                f"[TAGS] Sample sheet {sample_sheet.full_path} has already the correct tag"
            )
            return
        new_tags = [
            tag for tag in sample_sheet.tags if tag != self.archived_sample_sheet_tag
        ]
        new_tags.append(self.sample_sheet_tag)
        if not self.dry_run:
            sample_sheet.tags = new_tags
            print(f"[TAGS] Updated tags for file {sample_sheet.full_path}")
        else:
            print(
                f"[TAGS-dry-run] Would have updated tags for file {sample_sheet.full_path}"
            )

    def move_file_to_hk_bundle(self, file: File, bundle: str):
        """Change the location of the file to the Housekeeper bundle."""
        if file.is_included:
            print(f"[MOVE] The file {file.full_path} is already in the bundle")
            return
        if not os.path.exists(self.file_production_path(file=file)):
            if not self.dry_run:
                print(
                    f"[MOVE] File {file.full_path} does not exist in hasta,"
                    " deleting entry from Housekeeper"
                )
                self.hk_api.delete_file(file_id=file.id)
            else:
                print(
                    f"[MOVE-dry-run] File {file.full_path} does not exist in hasta,"
                    " would have deleted entry from Housekeeper"
                )
            return
        version: Version = self.hk_api.get_latest_bundle_version(bundle_name=bundle)
        if not self.dry_run:
            self.hk_api.include_file(file_obj=file, version_obj=version)
        else:
            print(
                f"[MOVE-dry-run] Would have moved sample sheet from {file.full_path}"
                " to a Housekeeper bundle"
            )

    def update_all_sample_sheets(self):
        """Update all bundles to have a 'samplesheet' instead of an 'archived_sample_sheet'."""
        for bundle in self.bundles:
            print(f"[START] Bundle {bundle}")
            sample_sheets: list[File] = self.get_sample_sheets_for_bundle(bundle=bundle)
            latest_sample_sheet: File = self.get_latest_file(files=sample_sheets)
            sample_sheets.remove(latest_sample_sheet)
            self.delete_files(files=sample_sheets)
            self.update_sample_sheet_tag(sample_sheet=latest_sample_sheet)
            self.move_file_to_hk_bundle(file=latest_sample_sheet, bundle=bundle)


def main(env: str, dry_run: bool):
    if env == "stage":
        hk_api: HousekeeperAPI = get_hk_api_stage()
    elif env == "production":
        hk_api: HousekeeperAPI = get_hk_api_prod()
    else:
        raise Exception(f"Invalid value for env: '{env}'")

    updater = SampleSheetTagUpdater(hk_api=hk_api, dry_run=dry_run)
    updater.update_all_sample_sheets()

    if not dry_run:
        hk_api.commit()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python remove_archived_sample_sheets.py env, dry_run")
    else:
        env = sys.argv[1]
        dry_run = False if sys.argv[2].lower() in ["0", "false"] else True
        print("======================== STARTING ======================")
        print(f"Setting environment to {env}")
        print(f"Setting dry run to {dry_run}")
        main(env=env, dry_run=dry_run)
        print("================= FINISHED SUCCESSFULLY =================")

```
- [ ] Delete tag "archived_sample_sheet" (using https://github.com/Clinical-Genomics/housekeeper/pull/163)
- [x] Change any remaining logic in cg that involves `archived_sample_sheet` https://github.com/Clinical-Genomics/cg/pull/2604

## Thi issue can be closed when
Files tagged with `archived_sample_sheets` are re-tagged with `sample_sheet`

**Comment by ChrOertlin** [comment]
Looks good to me. I suppose we would also remove the tag from the "Tags" table?

**Comment by diitaz93** [comment]
> Looks good to me. I suppose we would also remove the tag from the "Tags" table?

@ChrOertlin Correct, that part is still missing to implement

**Comment by Vince-janv** [comment]
I find the Main part quite hard to understand. I think it could be split into smaller functions. I know it's just a one time script but for the reviewers sake I think it would be safer.
Something like:
```python
bundles = get_all_flow_cell_bundles()
for bundle in bundles:
    sample_sheets = get_get_all_samplesheets_from_bundle(bundle)
    if len(samplesheets)==1:
        continue
    latest_latest_samplesheet=get_latest_samplesheet(sample_sheets)
    sample_sheets.remove(latest_latest_samplesheet)
    delete_samplesheets(sample_sheets)
```

Also, why do we assume there is only one file with the tag `samplesheet` and that that one is the one we want to keep? Would it not be easier to just bundle all `samplesheet` and `archived_samplesheet` into a list and just pick the newest one?

**Comment by islean** [comment]
Will continue looking tomorrow but the type hints here should probably be `list[str]`

```Python
sample_sheet_bundles: list[Bundle] = [
        file.version.bundle.name for file in sample_sheet_tag.files
    ]
    archived_sample_sheet_bundles: list[Bundle] = [
        file.version.bundle.name for file in archived_sample_sheet_tag.files
    ]
```

**Comment by seallard** [comment]
Some stuff sorted by importance:
- `update_sample_sheet_tag` will fail, needs to use `self.dry_run` instead of just `dry_run`.
- The `delete_files` function says it is supposed to delete the file from Hasta as well, but it only seems to delete it from housekeeper.
- Can we be sure that `getmtime` will be an accurate reflection of which the latest version of the sample sheet is?
- numpy and Version imports are not used.
- Don't set "archived_sample_sheet" and "archived_sample_sheet" as attributes, just send them into the function call

**Comment by islean** [comment]
> Some stuff sorted by importance:
> 
>     * `update_sample_sheet_tag` will fail, needs to use `self.dry_run` instead of just `dry_run`.
> 
>     * The `delete_files` function says it is supposed to delete the file from Hasta as well, but it only seems to delete it from housekeeper.
> 
>     * Can we be sure that `getmtime` will be an accurate reflection of which the latest version of the sample sheet is?
> 
>     * numpy and Version imports are not used.
> 
>     * Don't set "archived_sample_sheet" and "archived_sample_sheet" as attributes, just send them into the function call

I agree with much of what you are saying but numpy is used for `np.unique` although I am a bit uncertain of what the difference would be from just casting to a set.

**Comment by islean** [comment]
But I am a bit uncertain of what would be best - would looking at the version or `getmtime` give the most accurate reflection of "latest" sample sheet?

**Comment by diitaz93** [comment]
> Some stuff sorted by importance:
> 
> * `update_sample_sheet_tag` will fail, needs to use `self.dry_run` instead of just `dry_run`.

fixed
> * The `delete_files` function says it is supposed to delete the file from Hasta as well, but it only seems to delete it from housekeeper.

fixed, it is supposed to only remove from HK, the removal from hasta can be done later as it is the removal of the folder `/home/proj/production/sample_sheets/`
> * Can we be sure that `getmtime` will be an accurate reflection of which the latest version of the sample sheet is?

Yes, that is what we discussed this morning in the stand-up
> * numpy and Version imports are not used.

np.unique and Version for type hints
> * Don't set "archived_sample_sheet" and "archived_sample_sheet" as attributes, just send them into the function call

why?
> * get_hk_api_prod and get_hk_api_stage are redundant

details removed as the passwords are the difference, the real code has the differences

**Comment by islean** [comment]
Suggestion:

`if "housekeeper-bundles" not in file.full_path:`
=>
`if not file.is_included`

**Comment by islean** [comment]
Also - just saw that the `getmtime` is used on files which are all from the latest version. So that all sounds good.

**Comment by islean** [comment]
Can it happen that we have sample sheets which are not in the latest bundle version? If so, we could run into trouble, since those sample sheets won't  be returned from `get_sample_sheets_for_bundle`.

**Comment by diitaz93** [comment]
> Can it happen that we have sample sheets which are not in the latest bundle version? If so, we could run into trouble, since those sample sheets won't be returned from `get_sample_sheets_for_bundle`.

I found out that all bundles of interest have only one version using:
```python
for bundle in bundles:
    if len(bundle.versions) != 1:
        print(bundle.name)
```
It didn't print anything

**Comment by Vince-janv** [comment]
I found this much clearer to read, well done! I can't find anything to object to if all comments are addressed 🙌

**Comment by diitaz93** [comment]
Ran on stage, worked without any issues

**Comment by diitaz93** [comment]
Ran on production without issues

**Comment by diitaz93** [comment]
Ran:
```shell
[js.diazboada@hasta:~] [P_base] 9s $ housekeeper delete tag --name archived_sample_sheet
2023-10-25 13:40:27 hasta.scilifelab.se housekeeper.cli.core[59190] INFO Use root path /home/proj/production/housekeeper-bundles
Delete tag archived_sample_sheet with 0 associated files? [y/N]: y
2023-10-25 13:40:32 hasta.scilifelab.se housekeeper.cli.delete[59190] INFO Tag archived_sample_sheet deleted
θ64° [js.diazboada@hasta:~] [P_base] 11s $
```
on stage and production
