### ISSUE TITLE
Improve housekeeper CLI visualisation

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/housekeeper#197]
### User story
As a production user,
I would want `housekeeper get bundle` to always show the files, and the text to be legible,
so that i don't always need to add the -v flag or squint to be able to read blue text

### Acceptance criteria
- [x] All files are listed by default when using `housekeeper get bundle`
- [x] The text is clearly legible against the black background

#### Current look:
![Screenshot 2024-04-26 at 15 41 13](https://github.com/Clinical-Genomics/housekeeper/assets/69356202/317d41c8-eee4-48e9-a277-802d9a45d3cd)

#### Improved look?
<img width="347" alt="Screenshot 2024-04-29 at 09 08 51" src="https://github.com/Clinical-Genomics/housekeeper/assets/69356202/768327b1-2f1d-494a-b559-71db3ed918ba">

**Comment by seallard** [comment]
I think this has been addressed @Vince-janv
