### ISSUE TITLE
MIP 5 support

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/housekeeper#25]
Support new output:

- [x] peddy - "peddy.ped" ask @moonso => send to Scout
- [ ] pick up new merged SV file (might be in same location)

**Comment by robinandeer** [comment]
@henrikstranneheim: which file is the merged SV file in sample info?

**Comment by henrikstranneheim** [comment]
svdb:
    outdirectory: BETA/customers/cust000/643594-testset/analysis/643594-testset/bwa
    outfile: 643594-testset_sorted_md_brecal_comb_SV.vcf

**Comment by robinandeer** [comment]
@henrikstranneheim: Do we still need the merged SV files in addition to the BCF file? Do we need both or just one?

**Comment by ingkebil** [comment]
Closing. I guess we are not needing this anymore now that MIP6.0 is on the horizon
