### ISSUE TITLE
Extraction of specific QC metrics from the mip-analysis

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/housekeeper#32]
I would like to have the AT_dropout and GC_dropout numbers extracted from the qc_metrics file and store in the trend db

**Comment by ingkebil** [comment]
Should not be in housekeeper tho.  HK's only job is to provide and tag
files. This should be moved to the vogue or cg package.

wkr,
Kenny
--
Composed and sent on the road

**Comment by henrikstranneheim** [comment]
@emiliaol Move this to trailblazer and close this issue in hk

**Comment by henrikstranneheim** [comment]
Add to issue: 
collecthsmetrics:AT_DROPOUT & GC_DROPOUT
collectmultiplemetricsinsertsize: MEDIAN_INSERT_SIZE & STANDARD_DEVIATION

**Comment by henrikstranneheim** [comment]
Done in latest PR for Trailblazer
