### ISSUE TITLE
Add correct tags for really old cases

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/housekeeper#34]
Old cases have tags that are not on use or that have been renamed, e.g. vcf-snv-clinical -> vcf-snv-clinical. This prevents old cases that are in HK to be uploaded into scout (as scout does not find the correctly tagged files).

See bioit#167

- [ ] create mapping list to map old tags onto current ones
- [ ] add those tags to all old cases

**Comment by moonso** [comment]
Is this still valid @barrystokman @patrikgrenfeldt ? Could you close or add some information and proper labels?

**Comment by moonso** [comment]
Since there is no action I'm closing this. Feel free to reopen and add information if this is still relevant
