### ISSUE TITLE
cg upload auto fails: version/bundle not found in hk

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/housekeeper#44]
cron job that runs ```cg upload auto``` fails, see screenshot below

![image](https://user-images.githubusercontent.com/26384108/51730965-be754980-2079-11e9-8e6e-287d8c224da3.png)

**Comment by moonso** [comment]
Is this still a problem @barrystokman @patrikgrenfeldt @henrikstranneheim ? In that case perhaps you can add the proper labels and a suggested solution?

**Comment by barrystokman** [comment]
Quick search of clinical-logwatch emails yields no results for this error, so it's been solved or the issue is obsolete. Labeled `invalid` :)

I vote to close the issue.

**Comment by moonso** [comment]
Lets reopen if we encounter the problems again
