### ISSUE TITLE
RNA analysis output is stored in housekeeper

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/housekeeper#49]
As a prod bioinfo team memeber I want the relevant results from the rd_rna analysis to be saved in housekeeper, so that I know where to find them when doing deliveries (and they are saved for the future)

Problem description: 
1. Analysis files to be saved have not been defined
2. housekeeper does not know to pick these up. There are no tags created to be used either.
3. The bundle logic needs to be implemented for RNA analysis

Suggested solution:
1. Team MIP should specify: keys in sample_info. We decide tag. Action @Emilia-Ottosson-Laakso
2. See 1. Create bundle and push to HK based on tag (in cg/cli). 
3. We need to create a parse_sample_info for RNA in tb.py in cg.

```
cg->cli->TB->parse_config
       -> tb_api->create_bundle
  ->apps/mip/files.py
```
- detect the kind of analysis to be stored based on analysis_type
- rename parse_config to parse_sampleInfo (if that is what it actually parses)
- copy parse_config into `apps/mip/files.py`
- copy create_bundle into `meta/store/miprdrna.py`
- make sure MIP 7 rd DNA code is intact - because the current content of HK should remain intact

4. Documentation not needed - because we don't change MIP7 rd DNA code

DoD:
1. Verification done.
1. RNA analysis stored in HK based on new tag(s)

How to demo:
1. run `cg store analyis` on RNA case
1. show HK: `housekeeper get -V <case_id>`

**Comment by barrystokman** [comment]
![2019_10_21 10_36 Office Lens.jpg](https://zube.io/files/clinical-genomics/9ed87b1d35ac0ee1e0d007955a6239b9-2019_10_21-10_36-office-lens.jpg)

.

**Comment by barrystokman** [comment]
@henrikstranneheim @jemten @emiliaol 
Deployed!

**Comment by henrikstranneheim** [comment]
🎉 🍾

**Comment by vwirta** [comment]
Nice!
