### ISSUE TITLE
Add the same fastq-files for different sample names

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/housekeeper#53]
Sometimes it would be good to be able to link the same fastq-files for different sample-id's to be able to compare for example two different analyses.

**Comment by moonso** [comment]
Could you write a more detailed description of how you would like this to work and how to use it?

**Comment by moonso** [comment]
@emmser to implement this I need some more information so that it is possible to create a test case with the situation described. Could you add that or close this if it is not of interest anymore?

**Comment by emmser** [comment]
Don't remember why.
