### ISSUE TITLE
Housekeeper delete bundle only deletes the latest version

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/housekeeper#57]
`housekeeper delete bundle` deletes the latest version of the bundle, not the whole bundle which creates problems some times. For example when doing `cg transfer flowcell` when one sample has had a HK bundle that was removed, see screen shot from such a case and the solution to it. 

There was a PR suggesting a change to this command: [https://github.com/Clinical-Genomics/housekeeper/pull/36](url). The preferred way of this command would be to have two options: delete the latest version or delete the whole bundle. 

<img width="1440" alt="Screenshot 2020-03-02 at 16 30 39" src="https://user-images.githubusercontent.com/19236050/76491143-5294a280-642d-11ea-849d-c2d8128ad35f.png">

**Comment by moonso** [comment]
Ok I will follow this up

**Comment by moonso** [comment]
Fixed in #71
