### ISSUE TITLE
Delivery packages for cancer workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/housekeeper#59]
Could only assign this to one repo.

**Comment by moonso** [comment]
What does this mean and why is it here?

**Comment by annaengstrom** [comment]
@emmser @keyvanelhami @hassanfa please update or close if this should not be in this repo.

**Comment by hassanfa** [comment]
@moonso I think is related to cancer_in_prod project. I think the driver is Emma, maybe she can confirm if this is a good location or not?

@annaengstrom I don't know to be honest. Let's wait for Måns to respond.

**Comment by moonso** [comment]
So we have decided to keep projects in repositories. To create a project follow the guide here: https://github.com/Clinical-Genomics/cgp-project-template 

When that is ready you can open the issue in the project. This issue, as described here, is not related to Housekeeper so it should be closed here or transfered

**Comment by annaengstrom** [comment]
The project for data management is created in the same way as I did for cancer implemented in production.

https://github.com/orgs/Clinical-Genomics/projects/23

What is the difference? There is no project yet on Github, but appart from that, the issues are linked to different repos. Shouldn't they be?

**Comment by annaengstrom** [comment]
I updated the cancer project according to the project plan on [Drive](https://docs.google.com/document/d/1N4oTgJK4J0vOg7x5vlgT24TIdkJrhckxLNnmTb7fiA0/edit#heading=h.c62k5p8wnot), but it is probably easier if @emmser updates the issues to correct repo.

**Comment by moonso** [comment]
This now lives here: https://github.com/Clinical-Genomics/cgp-cancer-in-weekly-production/issues/10
