### ISSUE TITLE
Housekeeper is built around deprecated packages

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/housekeeper#60]
As most probably know there are core packages in housekeeper that are deprecated. This will inevitable lead to dependency conflicts and problems in general. We need a someone(s) to take care of this and update to use living code.

## List of deprecated packages

- [x] [Alchy][alchy]
- [x] [Flask-Alchy][flask-alchy]
- [x] [python-dateutil][python-dateutil] (fixed in #64 )

## How to replace

Alchy recommends [sqlservice][sql-service], however it does not seem to have a big community around it.

## Priority

This should at least have medium priority since it is really one of the core packages for CG

[alchy]: https://github.com/dgilland/alchy
[flask-alchy]: https://github.com/dgilland/flask-alchy
[python-dateutil]: https://github.com/paxan/python-dateutil
[marshmallow]: https://github.com/marshmallow-code/marshmallow
[marshmallow-sqlalchemy]:https://github.com/marshmallow-code/marshmallow-sqlalchemy
[sql-service]: https://github.com/dgilland/sqlservice

**Comment by henrikstranneheim** [comment]
Done
