### ISSUE TITLE
Adding files to housekeeper that doesn't exist 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/housekeeper#69]
When running below command, I did add a file to housekeeper that didn't existed. Housekeeper didn't gave any errors and it would be great if an error would appear if the file didn't exist:

```housekeeper add file -t fastq neatlyfastraven /home/proj/production/cancer/cases/quickzebra/fastq/downsampled/concatenated_ACC6408A6_XXXXXX_R3_.fastq.gz```

**Comment by moonso** [comment]
Can you show that the file does not exist by doing:

```ls /home/proj/production/cancer/cases/quickzebra/fastq/downsampled/concatenated_ACC6408A6_XXXXXX_R3_.fastq.gz```
?

**Comment by moonso** [comment]
Sorry, this is a bug. You are right.
