### ISSUE TITLE
New code owner

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/housekeeper#72]
Me and @Mropat had a chat yesterday and after some thinking I think it would be a good idea to add @Mropat as a code owner to housekeeper. I know @barrystokman is on vacation now and can not object but are you fine with that @henrikstranneheim , @patrikgrenfeldt ?

**Comment by henrikstranneheim** [comment]
Excellent!

**Comment by moonso** [comment]
Done

**Comment by patrikgrenfeldt** [comment]
I guess we're talking about being admin? Otherwise there should be a PR for the CODEOWNERS file? I suggest admins are the primary responsible and deputy in 1098. I guess she could be made that as well then?

**Comment by moonso** [comment]
>  guess we're talking about being admin? Otherwise there should be a PR for the CODEOWNERS file? I suggest admins are the primary responsible and deputy in 1098. I guess she could be made that as well then?

See #73 . I don't know about responsible and deputy, guess we will wait for @barrystokman to discuss that. Right now I think it's perfect if @Mropat is code owner so we can keep on developing without waiting for Barry

**Comment by patrikgrenfeldt** [comment]
I think that's great, welcome to Housekeeper @Mropat!

**Comment by Mropat** [comment]
Exciting stuff, thank you!
