### ISSUE TITLE
Integrate Housekeeper tables and data into clinical-db

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/housekeeper#86]
Housekeeper does not make sense as an independent package in CG infrastructure

- There is a HousekeeperAPI class in cg which contains Housekeeper's native API (Store) as well as additional housekeeper functionality
- cg uses Housekeeper for most operations
- Housekeeper still installed in save env as cg
- Housekeeper is not well maintained but is a versioned dependency of cg
- Data is duplicated between cg Analysis table and Housekeeper
- Deprecating Alchy can be done in both packages can be done on one motion

- We should consider doing this before the move to VM

This issue can be closed when 
- [ ] Housekeeper becomes part of cg and is archived

**Comment by henrikstranneheim** [comment]
Stale
