### ISSUE TITLE
Add option --keep-file to delete file

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/housekeeper#98]
Currently, `housekeeper delete file` removes the file from both the database and the system (i.e. removes the actual file). It would be nice to be able to delete only HK links from the database but to keep the actual files in the system.

**Comment by ivadym** [comment]
You have it already in `delete files` (plural). You can use `housekeeper delete files -b <bundle> -t <tags> -n` with the n flag:

```
-n, --notondisk           rm db entry from files not on disk
```

**Comment by fevac** [comment]
Oh! I missed that. Thank you. Closing
